### PR TITLE
fix: replace sync-exec package with child_process.execSync

### PR DESCRIPTION
**Pull request by fvera87**

### CODE REVIEW

**Comment by ChrisPearce** [comment]
@zeke, Would it be possible to create a new release (i.e. greater than v2.1.1) that includes this merged pull request?

**Comment by zeke** [comment]
Hey @ChrisPearce sorry about that. This project is set up with `semantic-release` but it appears to be broken.

I just pushed up a test commit to see if it will trigger a release: https://github.com/zeke/package-json-to-readme/commit/5320c4bdc87c8b065cdd9def3376eaf917d47111

**Comment by zeke** [comment]
👀 https://travis-ci.org/zeke/package-json-to-readme/builds/611634772

**Comment by zeke** [comment]
Failed! https://travis-ci.org/zeke/package-json-to-readme/jobs/611634776#L337

I think semantic-release needs to be upgraded and reconfigured.

**Pull request merged**
