### PR TITLE
set up semantic-release

### PR DESCRIPTION
**Pull request by zeke**

### CODE REVIEW

**Comment by zeke** [comment]
Followup to #25

**Comment by wmhilton** [comment]
How long does semantic-release take to set up? I should probably do this for all my projects, I've just been putting it off.

**Comment by zeke** [comment]
For you, a guide: https://gist.github.com/zeke/340a502ea9830cf66d47fa63aa0dad66

**Comment by wmhilton** [comment]
Sweet. If it really goes that smoothly I'll be a happy man!

**Pull request merged**
