### PR TITLE
Issue11

### PR DESCRIPTION
**Pull request by zkochan**
Used [mos](https://github.com/zkochan/mos) to generate some parts of the readme.

:warning: Had to update the required node js engine to v4

Added testing of the package's readme file.

Added support for more shields: npm, travis, coveralls, climate, deps, devDeps, peerDeps, gemnasium.

As a consequence of using mos to generate the readme, it is possible to update the readme after generation, by running `mos`. For instance, if a new dependency was installed, running mos in the console will add the new dependency to the dependencies section of the readme.

### CODE REVIEW

**Comment by zeke** [comment]
@zkochan this is awesome! Will review it soon.

**Comment by zkochan** [comment]
I was able to remove the dependency upon hogan.js by passing a markdown AST to mos

**Comment by wmhilton** [comment]
I like the ability to regenerate/update the README contents that mos provides. But I'm not thrilled with the fact that it require yet-another-template-language - and one that lives inside HTML comments like the old IE nasty tags...

```
<!--@h1([pkg.name])-->
<!--/@-->

<!--[if IE 6]>
<![endif]--> 
```

I actually read these things in vi over SSH and like the README.md to be clean as possible. With the exception of the badges, aren't all these categories possible to identify just from the `## Heading`? If we accepted some convention over flexibility, could we have auto updating README files without having to add the mos DSL code snippets to the README files?

**Comment by zkochan** [comment]
Yes, that was an old version of mos, later I've added the possibility to identify sections by headings

**Comment by wmhilton** [comment]
Oh that's pretty exciting! I've got to learn all these new tools they sound great!

**Comment by zeke** [comment]
Hey @zkochan sorry I let this PR go stale. Do you want to take a pass at updating this PR to use the new version of mos that identifies sections by headings?

**Comment by zkochan** [comment]
No problem. I'll try to update the PR.

**Comment by zeke** [comment]
Hey @zkochan. I'm going through my old PRs. Still want to take a shot at updating this?

**Comment by zkochan** [comment]
yes, it's just I am busy with [pnpm](https://github.com/rstacruz/pnpm) the last couple of months. If it makes you noise I can create a new PR later

**Comment by zeke** [comment]
pnpm looks like it's really coming along!

I'm gonna close this out. Feel free to re-open if decide to revisit this project. 👍

**Pull request closed without merging**
